config/routes.rb
Rails.application.routes.draw do

  root 'welcome#home'
  get 'welcome/link', to: 'welcome#link'
  resources :articles

end

app/models/article.rb
class Article < ActiveRecord::Base
  validates :title, presence:true, length:{ minimum:3, maximum:50 }
  validates :description, presence:true, length:{ minimum:10, maximum:500 }

end

app/models/user.rb
class User < ActiveRecord::Base
  validates :username, presence: true,
  uniqueness: { case_sensitive: false },
  length: { minimum: 3, maximum: 25 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 105 },
  uniqueness: { case_sensitive: false },
  format: { with: VALID_EMAIL_REGEX }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  def new
    @article=Article.new
  end

  def create
    @article =Article.new(article_params)
    if @article.save
      flash[:notice] ="Article was successfully created"
      redirect_to article_path(@article)
    else
      render 'new'
    end
  end

  def edit
    @article =Article.find(params[:id])
  end

  def update
    @article =Article.find(params[:id])
    if @article.update(article_params)
      flash[:notice] ="Article was succesfully edited"
      redirect_to article_path(@article)
    else
      render 'edit'
    end
  end

  def index
    @articles =Article.all
  end



  def show
    @article =Article.find(params[:id])
  end

  def destroy
    @article =Article.find(params[:id])
    @article.destroy
    flash[:notice] = "Article was successfully deleted"
    redirect_to articles_path
  end

  private
  def article_params
    params.require(:article).permit(:title, :description)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def home
  end
  def link
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/articles/_form.html.erb
<% if @article.errors.any? %>
<ul>
  <% @article.errors.full_messages.each do |msg| %>
  <li><%= msg %></li>
  <% end %>
</ul>
<% end %>

<%= form_for @article do |f| %>
<p>
  <%= f.label :제목 %><br/>
  <%= f.text_field :title %><br/>
</p>
<p>
  <%= f.label :description %><hr/>
  <%= f.text_area :description %><br/><br/>
  <%= f.submit %>
</p>

<% end %>

app/views/articles/edit.html.erb
<h1>Edit Articles</h1>
<h2 style="color:red"><b>Edit articles</b></h2>

<%= render 'form' %>

app/views/articles/index.html.erb
<h1 style="color:green;">Article List</h1>

<table>
  <tr>
    <%= link_to "새 파일 만들기", new_article_path %>
    <th>제목</th>
    <th>내용</th>
   </tr>
    <% @articles.each do |article| %>
      <tr>
       <td><%= article.title %></td>
       <td><%= article.description %></td>
        <td><%= link_to "파일 수정하기", edit_article_path(article) %></td>
        <td><%= link_to "파일 보여주기", article_path(article) %></td>
        <td><%= link_to "삭제", article_path(article), method: :delete, data: {confirm: "지우고 싶니??"} %></td>
        <br/>
  </tr>
</table>
  <% end %>

app/views/articles/new.html.erb
<h1>Create Articles</h1>
<h2 style="color:red"><b>Create articles</b></h2>

<%= render 'form' %>

app/views/articles/show.html.erb
<h1>Showing selected article</h1>

<p>
  Title= <%= @article.title %>
</p>
<p>
  Description= <%= @article.description %>
</p>

<%= link_to "Edit this article", edit_article_path(@article) %>
<%= link_to "Back to articles listing", articles_path %>

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <ul>
    <li><%= msg %></li>
  </ul>
  <% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>AlphaBlog</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= render 'layouts/messages' %>
  <%= yield %>

</body>
</html>

app/views/welcome/home.html.erb
<html>
  <head>
    <title>This is home</title>
    <style>
      a {background-color:white; color:black; }
      p {color: blue;background-color:white; text-align:left;}
      h1 {background-color:gray;color: white; text-align:center;font-size:200%;}
      table,th,tr,td
      {
        color: red;
        padding: 10px;
          border: 2px solid blue;
          text-align:center;
        border-collapse: collapse;
        background-color:yellow;
      }
    </style>
  </head>
  <body>
    <h1><b>Welcome to my Home!!</b></h1>
    <h2><%= link_to "Alpha_blog", articles_path %></h2>
    <p>
    <a href="http://www.naver.com" target="_blank">네이버</a>
    <br>
    <a href="http://www.daum.net", target="_parent">다음</a>
    <br>
    </p>

    <address style="float:right;color:white;background-color:black">
      <h2><b>A warm-hearted illusion</b></h2>
      <p>
               <ui>
                 <li>
                   On Dec. 8, a new edition of Adolf Hitler’s “Mein Kampf,” or “My Struggle,” was republished in Germany 70 years after it went out of print. The book is an autobiographical                       political manifesto of the Nazi dictator, who was imprisoned for the Munich Beer Hall revolt in 1925 when he was 36.
                 </li>
                 <li>
                   After the fall of Nazi Germany, the state of Bavaria had the copyright and refused to publish it, making it virtually banned. The copyright expired at the end of last year -                     70 years after the author’s death - and the Institute of Contemporary History republished the book to facilitate accurate understanding of Nazism to prevent extreme racism.
                 </li>
                 <li>
                   In Germany and the international community, banning the publication of “Mein Kampf” was described as a symbol of Germany’s conscience. Unlike unapologetic Japan, Germany was                     considered to be strict on further discussing Nazism by making the book inaccessible. As this notorious book was republished, the international media considers it a measure                     to properly condemn Nazism. Whether the book is banned or the ban is lifted, Germany is always treated as a model nation.
                 </li>
                 <li>
                 But is Germany really exemplary? Lift the cover of the hidden parts of the history, and the ugly face of Germany is exposed. In 1904, Germany massacred the Herero and Nama tri                  bes to expand in German South West Africa, which is modern day Namibia. The German army poisoned wells in the area. In the first genocide of the 20th century, 65,000 of the 8                  0,000 Herero and 10,000 of the 20,000 Nama people were killed.
                 </li>
                 <li>
                   Moreover, Germany put 2,000 survivors into concentration camps for medical experiments on race. Later, their corpses were brought to Germany for further experimentation, and                   20 remains were returned to Namibia in 2011.
                 </li>
               </ui>
      </p>
    </address>


    <address style="color:white">
      a<br>
      <br>
    </address>



    <table>
      <tr>
        <td>한국</td>
        <td>일본</td>
        <td>중국</td>
      </tr>
      <tr>
        <td>한글</td>
        <td>히라가나</td>
        <td>중궈</td>
      </tr>
      <tr>
        <td>1</td>
        <td>2</td>
        <td>3</td>
      </tr>
    </table>
    <br>

    <ui>
      <li>사과</li>
      <li>배</li>
      <li>딸기</li>
    </ui>
    <br>

  </body>
</html>

<%= link_to '링크로 가는 길', welcome_link_path %>

app/views/welcome/link.html.erb
<h2>링크페이지</h2>

<%=link_to '홈으로가는길', root_path %>